# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='short_name',
            field=models.CharField(default=' ', max_length=5),
            preserve_default=False,
        ),
    ]
