# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_building_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=100, max_length=5),
            preserve_default=False,
        ),
    ]
