# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyfako_core', '0002_remove_member_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='psyfakomensch', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
