# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyfako_core', '0003_auto_20161123_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_citycode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_streetnumber',
            field=models.IntegerField(blank=True),
        ),
    ]
