# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psyfako_core', '0004_auto_20161124_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fachschaft',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='psyfako_core.Fachschaft'),
        ),
    ]
