# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conmessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chat_id', models.IntegerField()),
                ('chat_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='Channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='conmessages.Channel'),
        ),
    ]
