# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conmessages', '0002_auto_20161205_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Channel',
            new_name='channel',
        ),
    ]
