# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_building_short_name'),
        ('timetable', '0003_auto_20161123_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
            preserve_default=False,
        ),
    ]
