# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_workgroup_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='group_type',
            field=models.CharField(choices=[('D', 'Diskussion'), ('P', 'Positionspapier')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
