# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240)),
                ('iteration', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Fachschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=240)),
                ('university_type', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=240)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(blank=True, max_length=240)),
                ('address_streetnumber', models.IntegerField()),
                ('address_city', models.CharField(blank=True, max_length=240)),
                ('address_citycode', models.IntegerField()),
                ('mobilephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('mail', models.EmailField(max_length=254)),
                ('fachschaft', models.CharField(blank=True, max_length=240)),
                ('is_konrat', models.BooleanField(default=False)),
                ('is_vorstand', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
