# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fachschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_core.Fachschaft'),
        ),
    ]
